export const MOCK_QUEST_DATA = [
  {
    img: 'https://info.monsterhunter.com/wilds/event-quest/thumbnail/mst-quest/March2025/JhhTlmvAogVbRlzdAHcv.jpg',
    difficulty: 8,
    questName: 'The Shining Storm Rages',
    locales: 'Windward Plains',
    targetMonster: 'Rey Dau',
    variant: 'arch-tempered',
    questType: 'slay',
    amount: 1,
    startAt: '2025-07-05T00:00:00.000Z',
    endAt: '2026-09-04T23:59:00.000Z',
    requiredRank: 50,
  },
  {
    img: 'https://info.monsterhunter.com/wilds/event-quest/thumbnail/mst-quest/February2025/tzOMg5CCDyLMTyG0EFUX.jpg',
    difficulty: 5,
    questName: 'Sand-Scarred Soul',
    locales: 'Windward Plains',
    targetMonster: 'Doshaguma',
    variant: 'normal',
    questType: 'hunt',
    amount: 1,
    startAt: '2026-02-05T00:00:00.000Z',
    endAt: '2026-09-04T23:59:00.000Z',
    requiredRank: 9,
  },
] as const;

export const MOCK_QUEST_DATA_2 = {
  img: 'https://info.monsterhunter.com/wilds/event-quest/thumbnail/mst-quest/March2025/JhhTlmvAogVbRlzdAHcv.jpg',
  difficulty: 8,
  questName: 'The Shining Storm Rages',
  locales: 'Windward Plains',
  targetMonster: 'Rey Dau',
  variant: 'arch-tempered',
  questType: 'slay',
  amount: 1,
  startAt: '2025-07-05T00:00:00.000Z',
  endAt: '2026-09-04T23:59:00.000Z',
  requiredRank: 50,
};
